workflows:
  android-build:
    name: Build APK
    environment:
      java: 17
    scripts:
      - unzip StokPenjualanOffline-Android.zip
      - cd $(find . -type d -name "app" | head -1 | xargs dirname)
      - pwd
      - gradle assembleDebug --stacktrace
    artifacts:
      - '**/app/build/outputs/apk/debug/*.apk'
