workflows:
  android-build:
    name: Build APK
    environment:
      java: 17
    scripts:
      - name: Unzip Project
        script: unzip StokPenjualanOffline-Android.zip
      - name: List Files
        script: ls -R
      - name: Find Project Folder
        script: |
          PROJECT_DIR=$(find . -name "build.gradle.kts" | head -1 | xargs dirname)
          echo "Found project in: $PROJECT_DIR"
          cd "$PROJECT_DIR"
          pwd
          gradle assembleDebug --stacktrace
    artifacts:
      - '**/app/build/outputs/apk/debug/*.apk'
