workflows:
  android-build:
    name: Build APK Android
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - google_credentials
    scripts:
      - name: Unzip Project
        script: |
          unzip StokPenjualanOffline-Android.zip -d project
          cd project
          ls -la
      - name: Build APK
        script: |
          cd project
          ./gradlew assembleDebug
    artifacts:
      - project/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - dzheekodzokers-prog
